name: Backend github action workflows

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'starter/backend/**'
defaults:
  run:
    working-directory: starter/backend
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: set up python 
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: cache pipenv
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-${{ matrix.python-version }}-pipenv-${{ hashFiles('starter/backend/Pipfile.lock') }}
      - name: install dependencies
        working-directory: ./starter/backend
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        env:
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv install --dev
      - name: run lint
        working-directory: ./starter/backend
        run: |
          pipenv run lint     
        continue-on-error: false          
