name: Frontend github action workflow

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'starter/frontend/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18.14'
      - name: Install Dependencies
        run: cd starter/frontend && npm ci
      - name: Lint
        run: cd starter/frontend && npm run lint        
        continue-on-error: false
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18.14'
      - name: Install Dependencies
        run: cd starter/frontend && npm ci
      - name: Run Tests
        run: cd starter/frontend && npm test
        continue-on-error: false

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Build front end application
        run: echo 'done successfully'
